org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.17
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=dcrapi
mod_name=DC Render API
mod_license=QSUP 1.0.0
mod_version=0.2.0-rc-1
mod_group_id=com.qituo.dcrapi
mod_authors=QiTuo,Yifei
mod_description=DC Render API: Custom graphics API powering exclusive visual effects for Dragon Curse Chronicles.
