modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Qituo,Yifei"
description='''
DC Render API: Custom graphics API powering exclusive visual effects for Dragon Curse Chronicles.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# KotlinForForge 依赖
[[dependencies.${mod_id}]]
    modId="kotlinforforge"
    type="required"
    versionRange="[5.12,)"
    ordering="AFTER"
    side="BOTH"
