# 增加 Gradle 可用内存
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# IntelliJ IDEA 暂不完全支持 configuration cache
org.gradle.configuration-cache=false

# Fabric 属性
# 检查 https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# 模组属性
mod_version=0.1.0-1.20.1Fabric
maven_group=com.qituo.dcrapi

# 依赖
fabric_api_version=0.92.11+1.20.1
# Fabric Kotlin Language Adapter 版本（自带 Kotlin 2.4.10 标准库）
fabric_kotlin_version=1.13.13+kotlin.2.4.10
